package cn.leaves.websnap.batis.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import cn.leaves.websnap.batis.entity.Pagecollectcontent;

public class PagecollectcontentSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageCollectContent
     *
     * @mbggenerated
     */
    public String insertSelective(Pagecollectcontent record) {
        BEGIN();
        INSERT_INTO("pageCollectContent");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getPageid() != null) {
            VALUES("pageId", "#{pageid,jdbcType=BIGINT}");
        }
        
        if (record.getContentruleid() != null) {
            VALUES("contentRuleId", "#{contentruleid,jdbcType=BIGINT}");
        }
        
        if (record.getContent() != null) {
            VALUES("content", "#{content,jdbcType=LONGVARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageCollectContent
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(Pagecollectcontent record) {
        BEGIN();
        UPDATE("pageCollectContent");
        
        if (record.getPageid() != null) {
            SET("pageId = #{pageid,jdbcType=BIGINT}");
        }
        
        if (record.getContentruleid() != null) {
            SET("contentRuleId = #{contentruleid,jdbcType=BIGINT}");
        }
        
        if (record.getContent() != null) {
            SET("content = #{content,jdbcType=LONGVARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=BIGINT}");
        
        return SQL();
    }
}