package cn.leaves.websnap.batis.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import cn.leaves.websnap.batis.entity.Page;

public class PageSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbggenerated
     */
    public String insertSelective(Page record) {
        BEGIN();
        INSERT_INTO("page");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getSeedid() != null) {
            VALUES("seedId", "#{seedid,jdbcType=BIGINT}");
        }
        
        if (record.getTitle() != null) {
            VALUES("title", "#{title,jdbcType=VARCHAR}");
        }
        if (record.getWeburl() != null) {
            VALUES("weburl", "#{weburl,jdbcType=VARCHAR}");
        }

        if (record.getFetchtime() != null) {
            VALUES("fetchTime", "#{fetchtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getHascontent() != null) {
            VALUES("hasContent", "#{hascontent,jdbcType=BIT}");
        }
        
        if (record.getContent() != null) {
            VALUES("content", "#{content,jdbcType=LONGVARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(Page record) {
        BEGIN();
        UPDATE("page");
        
        if (record.getSeedid() != null) {
            SET("seedId = #{seedid,jdbcType=BIGINT}");
        }
        
        if (record.getWeburl() != null) {
            SET("weburl = #{weburl,jdbcType=VARCHAR}");
        }
        if (record.getTitle() != null) {
            SET("title = #{title,jdbcType=VARCHAR}");
        }

        if (record.getFetchtime() != null) {
            SET("fetchTime = #{fetchtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getHascontent() != null) {
            SET("hasContent = #{hascontent,jdbcType=BIT}");
        }
        
        if (record.getContent() != null) {
            SET("content = #{content,jdbcType=LONGVARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=BIGINT}");
        
        return SQL();
    }
}