package cn.leaves.websnap.batis.mapper;

import cn.leaves.websnap.batis.entity.Seed;

import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class SeedSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seed
     *
     * @mbggenerated
     */
    public String insertSelective(Seed record) {
        BEGIN();
        INSERT_INTO("seed");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getName() != null) {
            VALUES("name", "#{name,jdbcType=VARCHAR}");
        }

        if (record.getUrl() != null) {
            VALUES("url", "#{url,jdbcType=VARCHAR}");
        }
        
        if (record.getLastexecutetime() != null) {
            VALUES("lastExecuteTime", "#{lastexecutetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCron() != null) {
            VALUES("cron", "#{cron,jdbcType=BIGINT}");
        }
        
        if (record.getStatus() != null) {
            VALUES("status", "#{status,jdbcType=BIT}");
        }
        if (record.getNumberOfCrawler() != null) {
            VALUES("numberOfCrawler", "#{numberOfCrawler,jdbcType=VARCHAR}");
        }
        if (record.getCharset() != null) {
            VALUES("charset", "#{charset,jdbcType=VARCHAR}");
        }

        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seed
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(Seed record) {
        BEGIN();
        UPDATE("seed");

        if (record.getName() !=null) {
            SET("name = #{name, jdbcType=VARCHAR}");
        }
        
        if (record.getUrl() != null) {
            SET("url = #{url,jdbcType=VARCHAR}");
        }
        
        if (record.getLastexecutetime() != null) {
            SET("lastExecuteTime = #{lastexecutetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCron() != null) {
            SET("cron = #{cron,jdbcType=BIGINT}");
        }
        
        if (record.getStatus() != null) {
            SET("status = #{status,jdbcType=BIT}");
        }
        if (record.getNumberOfCrawler() != null) {
            VALUES("numberOfCrawler", "#{numberOfCrawler,jdbcType=VARCHAR}");
        }
        if (record.getCharset() != null) {
            VALUES("charset", "#{charset,jdbcType=VARCHAR}");
        }

        WHERE("id = #{id,jdbcType=BIGINT}");
        
        return SQL();
    }

    public String findBySelective(Seed record) {
        BEGIN();
        SELECT("*");
        FROM("seed");
        ORDER_BY("lastExecuteTime desc");
        return SQL();
    }
}