package cn.leaves.websnap.batis.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import cn.leaves.websnap.batis.entity.Seedpagerule;

public class SeedpageruleSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seedPageRule
     *
     * @mbggenerated
     */
    public String insertSelective(Seedpagerule record) {
        BEGIN();
        INSERT_INTO("seedPageRule");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getSeedid() != null) {
            VALUES("seedId", "#{seedid,jdbcType=BIGINT}");
        }
        
        if (record.getMatchtype() != null) {
            VALUES("matchType", "#{matchtype,jdbcType=VARCHAR}");
        }
        
        if (record.getPattern() != null) {
            VALUES("pattern", "#{pattern,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seedPageRule
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(Seedpagerule record) {
        BEGIN();
        UPDATE("seedPageRule");
        
        if (record.getSeedid() != null) {
            SET("seedId = #{seedid,jdbcType=BIGINT}");
        }
        
        if (record.getMatchtype() != null) {
            SET("matchType = #{matchtype,jdbcType=VARCHAR}");
        }
        
        if (record.getPattern() != null) {
            SET("pattern = #{pattern,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=BIGINT}");
        
        return SQL();
    }
}