package cn.leaves.websnap.batis.mapper;

import cn.leaves.websnap.batis.entity.Page;
import cn.leaves.websnap.batis.entity.Seed;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface SeedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seed
     *
     * @mbggenerated
     */
    @Delete({
        "delete from seed",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seed
     *
     * @mbggenerated
     */
    @Insert({
        "insert into seed (id, url, ",
        "lastExecuteTime, cron, ",
        "status, name, numberOfCrawler, charset)",
        "values (#{id,jdbcType=BIGINT}, #{url,jdbcType=VARCHAR}, ",
        "#{lastexecutetime,jdbcType=TIMESTAMP}, #{cron,jdbcType=BIGINT}, ",
        "#{status,jdbcType=BIT},#{name, jdbcType=VARCHAR},#{numberOfCrawler}, #{charset})"
    })
    int insert(Seed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seed
     *
     * @mbggenerated
     */
    @InsertProvider(type=SeedSqlProvider.class, method="insertSelective")
    int insertSelective(Seed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seed
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, url, lastExecuteTime, cron, status",
        "from seed",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="lastExecuteTime", property="lastexecutetime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="cron", property="cron", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.BIT),
        @Result(column = "numberOfCrawler", property = "numberOfCrawler", jdbcType = JdbcType.VARCHAR),
        @Result(column = "charset", property = "charset", jdbcType = JdbcType.VARCHAR)
    })
    Seed selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seed
     *
     * @mbggenerated
     */
    @UpdateProvider(type=SeedSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Seed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seed
     *
     * @mbggenerated
     */
    @Update({
        "update seed",
        "set url = #{url,jdbcType=VARCHAR},",
          "lastExecuteTime = #{lastexecutetime,jdbcType=TIMESTAMP},",
          "cron = #{cron,jdbcType=BIGINT},",
          "status = #{status,jdbcType=BIT}",
          "numberOfCrawler = #{numberOfCrawler,jdbcType=BIT}",
          "charset = #{charset,jdbcType=BIT}",
          "name = #{name}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Seed record);

    @Select({
            "select *",
            "from seed"
    })
    @Result(javaType = Seed.class)
    List<Seed> selectAll();

    @SelectProvider(type = SeedSqlProvider.class, method = "findBySelective")
    com.github.pagehelper.Page<Seed> findBySelective(Seed record);
}