package cn.leaves.websnap.batis.mapper;

import cn.leaves.websnap.batis.entity.Seedpagerule;
import com.github.pagehelper.Page;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface SeedpageruleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seedPageRule
     *
     * @mbggenerated
     */
    @Delete({
        "delete from seedPageRule",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seedPageRule
     *
     * @mbggenerated
     */
    @Insert({
        "insert into seedPageRule (id, seedId, ",
        "matchType, pattern)",
        "values (#{id,jdbcType=BIGINT}, #{seedid,jdbcType=BIGINT}, ",
        "#{matchtype,jdbcType=VARCHAR}, #{pattern,jdbcType=VARCHAR})"
    })
    int insert(Seedpagerule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seedPageRule
     *
     * @mbggenerated
     */
    @InsertProvider(type=SeedpageruleSqlProvider.class, method="insertSelective")
    int insertSelective(Seedpagerule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seedPageRule
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, seedId, matchType, pattern",
        "from seedPageRule",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="seedId", property="seedid", jdbcType=JdbcType.BIGINT),
        @Result(column="matchType", property="matchtype", jdbcType=JdbcType.VARCHAR),
        @Result(column="pattern", property="pattern", jdbcType=JdbcType.VARCHAR)
    })
    Seedpagerule selectByPrimaryKey(Long id);

    @Select({"select", "id, seedId, matchType, pattern", "from seedPageRule", "where id=#{id}"})
    Page<Seedpagerule> selectBySeedId(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seedPageRule
     *
     * @mbggenerated
     */
    @UpdateProvider(type=SeedpageruleSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Seedpagerule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seedPageRule
     *
     * @mbggenerated
     */
    @Update({
        "update seedPageRule",
        "set seedId = #{seedid,jdbcType=BIGINT},",
          "matchType = #{matchtype,jdbcType=VARCHAR},",
          "pattern = #{pattern,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Seedpagerule record);
}