package cn.leaves.websnap.batis.entity;

import java.util.Date;

public class Page {

    public Page() {
    }

    public Page(Long seedid, String title, String weburl, Date fetchtime, Boolean hascontent) {
        this.seedid = seedid;
        this.title = title;
        this.weburl = weburl;
        this.fetchtime = fetchtime;
        this.hascontent = hascontent;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page.seedId
     *
     * @mbggenerated
     */
    private Long seedid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page.weburl
     *
     * @mbggenerated
     */

    private String title;

    private String weburl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page.fetchTime
     *
     * @mbggenerated
     */
    private Date fetchtime;

    private String fetchtimeString;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page.hasContent
     *
     * @mbggenerated
     */
    private Boolean hascontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page.id
     *
     * @return the value of page.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page.id
     *
     * @param id the value for page.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page.seedId
     *
     * @return the value of page.seedId
     *
     * @mbggenerated
     */
    public Long getSeedid() {
        return seedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page.seedId
     *
     * @param seedid the value for page.seedId
     *
     * @mbggenerated
     */
    public void setSeedid(Long seedid) {
        this.seedid = seedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page.weburl
     *
     * @return the value of page.weburl
     *
     * @mbggenerated
     */
    public String getWeburl() {
        return weburl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page.weburl
     *
     * @param weburl the value for page.weburl
     *
     * @mbggenerated
     */
    public void setWeburl(String weburl) {
        this.weburl = weburl == null ? null : weburl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page.fetchTime
     *
     * @return the value of page.fetchTime
     *
     * @mbggenerated
     */
    public Date getFetchtime() {
        return fetchtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page.fetchTime
     *
     * @param fetchtime the value for page.fetchTime
     *
     * @mbggenerated
     */
    public void setFetchtime(Date fetchtime) {
        this.fetchtime = fetchtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page.hasContent
     *
     * @return the value of page.hasContent
     *
     * @mbggenerated
     */
    public Boolean getHascontent() {
        return hascontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page.hasContent
     *
     * @param hascontent the value for page.hasContent
     *
     * @mbggenerated
     */
    public void setHascontent(Boolean hascontent) {
        this.hascontent = hascontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page.content
     *
     * @return the value of page.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page.content
     *
     * @param content the value for page.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getFetchtimeString() {
        return fetchtimeString;
    }

    public void setFetchtimeString(String fetchtimeString) {
        this.fetchtimeString = fetchtimeString;
    }
}