package cn.leaves.websnap.batis.entity;

public class Seedpagerule {

    public static final String MATCH_TYPE_ANT_STYLE = "antStyle";
    public static final String MATCH_TYPE_REGEX     = "regex";


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seedPageRule.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seedPageRule.seedId
     *
     * @mbggenerated
     */
    private Long seedid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seedPageRule.matchType
     *
     * @mbggenerated
     */
    private String matchtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seedPageRule.pattern
     *
     * @mbggenerated
     */
    private String pattern;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seedPageRule.id
     *
     * @return the value of seedPageRule.id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seedPageRule.id
     *
     * @param id the value for seedPageRule.id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seedPageRule.seedId
     *
     * @return the value of seedPageRule.seedId
     * @mbggenerated
     */
    public Long getSeedid() {
        return seedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seedPageRule.seedId
     *
     * @param seedid the value for seedPageRule.seedId
     * @mbggenerated
     */
    public void setSeedid(Long seedid) {
        this.seedid = seedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seedPageRule.matchType
     *
     * @return the value of seedPageRule.matchType
     * @mbggenerated
     */
    public String getMatchtype() {
        return matchtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seedPageRule.matchType
     *
     * @param matchtype the value for seedPageRule.matchType
     * @mbggenerated
     */
    public void setMatchtype(String matchtype) {
        this.matchtype = matchtype == null ? null : matchtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seedPageRule.pattern
     *
     * @return the value of seedPageRule.pattern
     * @mbggenerated
     */
    public String getPattern() {
        return pattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seedPageRule.pattern
     *
     * @param pattern the value for seedPageRule.pattern
     * @mbggenerated
     */
    public void setPattern(String pattern) {
        this.pattern = pattern == null ? null : pattern.trim();
    }
}