package cn.leaves.websnap.batis.entity;

import java.util.Date;

public class Seed {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seed.id
     *
     * @mbggenerated
     */
    private Long id;

    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seed.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seed.lastExecuteTime
     *
     * @mbggenerated
     */
    private Date lastexecutetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seed.cron
     *
     * @mbggenerated
     */
    private String cron;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seed.status
     *
     * @mbggenerated
     */
    private Boolean status;

    /**
     * 爬虫的数量
     */
    private Integer numberOfCrawler;

    /**
     * 编码
     */
    private String charset;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seed.id
     *
     * @return the value of seed.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seed.id
     *
     * @param id the value for seed.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seed.url
     *
     * @return the value of seed.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seed.url
     *
     * @param url the value for seed.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seed.lastExecuteTime
     *
     * @return the value of seed.lastExecuteTime
     *
     * @mbggenerated
     */
    public Date getLastexecutetime() {
        return lastexecutetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seed.lastExecuteTime
     *
     * @param lastexecutetime the value for seed.lastExecuteTime
     *
     * @mbggenerated
     */
    public void setLastexecutetime(Date lastexecutetime) {
        this.lastexecutetime = lastexecutetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seed.cron
     *
     * @return the value of seed.cron
     *
     * @mbggenerated
     */
    public String getCron() {
        return cron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seed.cron
     *
     * @param cron the value for seed.cron
     *
     * @mbggenerated
     */
    public void setCron(String cron) {
        this.cron = cron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seed.status
     *
     * @return the value of seed.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seed.status
     *
     * @param status the value for seed.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    public Integer getNumberOfCrawler() {
        return numberOfCrawler;
    }

    public void setNumberOfCrawler(Integer numberOfCrawler) {
        this.numberOfCrawler = numberOfCrawler;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return "Seed{" +
               "id=" + id +
               ", name='" + name + '\'' +
               ", url='" + url + '\'' +
               '}';
    }

    public String getCharset() {
        return charset;
    }

    public void setCharset(String charset) {
        this.charset = charset;
    }
}