package cn.leaves.websnap.batis.entity;

public class Seedcontentprocessrule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seedContentProcessRule.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seedContentProcessRule.seedId
     *
     * @mbggenerated
     */
    private Long pageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seedContentProcessRule.collectVar
     *
     * @mbggenerated
     */
    private String collectvar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seedContentProcessRule.collectType
     *
     * @mbggenerated
     */
    private String collecttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seedContentProcessRule.collectLabel
     *
     * @mbggenerated
     */
    private String collectlabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seedContentProcessRule.collectPattern
     *
     * @mbggenerated
     */
    private String collectpattern;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seedContentProcessRule.storage
     *
     * @mbggenerated
     */
    private Boolean storage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seedContentProcessRule.conditional
     *
     * @mbggenerated
     */
    private Boolean conditional;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seedContentProcessRule.conditionPattern
     *
     * @mbggenerated
     */
    private String conditionpattern;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seedContentProcessRule.id
     *
     * @return the value of seedContentProcessRule.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seedContentProcessRule.id
     *
     * @param id the value for seedContentProcessRule.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seedContentProcessRule.seedId
     *
     * @return the value of seedContentProcessRule.seedId
     *
     * @mbggenerated
     */
    public Long getPageid() {
        return pageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seedContentProcessRule.seedId
     *
     * @param pageid the value for seedContentProcessRule.seedId
     *
     * @mbggenerated
     */
    public void setPageid(Long pageid) {
        this.pageid = pageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seedContentProcessRule.collectVar
     *
     * @return the value of seedContentProcessRule.collectVar
     *
     * @mbggenerated
     */
    public String getCollectvar() {
        return collectvar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seedContentProcessRule.collectVar
     *
     * @param collectvar the value for seedContentProcessRule.collectVar
     *
     * @mbggenerated
     */
    public void setCollectvar(String collectvar) {
        this.collectvar = collectvar == null ? null : collectvar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seedContentProcessRule.collectType
     *
     * @return the value of seedContentProcessRule.collectType
     *
     * @mbggenerated
     */
    public String getCollecttype() {
        return collecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seedContentProcessRule.collectType
     *
     * @param collecttype the value for seedContentProcessRule.collectType
     *
     * @mbggenerated
     */
    public void setCollecttype(String collecttype) {
        this.collecttype = collecttype == null ? null : collecttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seedContentProcessRule.collectLabel
     *
     * @return the value of seedContentProcessRule.collectLabel
     *
     * @mbggenerated
     */
    public String getCollectlabel() {
        return collectlabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seedContentProcessRule.collectLabel
     *
     * @param collectlabel the value for seedContentProcessRule.collectLabel
     *
     * @mbggenerated
     */
    public void setCollectlabel(String collectlabel) {
        this.collectlabel = collectlabel == null ? null : collectlabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seedContentProcessRule.collectPattern
     *
     * @return the value of seedContentProcessRule.collectPattern
     *
     * @mbggenerated
     */
    public String getCollectpattern() {
        return collectpattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seedContentProcessRule.collectPattern
     *
     * @param collectpattern the value for seedContentProcessRule.collectPattern
     *
     * @mbggenerated
     */
    public void setCollectpattern(String collectpattern) {
        this.collectpattern = collectpattern == null ? null : collectpattern.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seedContentProcessRule.storage
     *
     * @return the value of seedContentProcessRule.storage
     *
     * @mbggenerated
     */
    public Boolean getStorage() {
        return storage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seedContentProcessRule.storage
     *
     * @param storage the value for seedContentProcessRule.storage
     *
     * @mbggenerated
     */
    public void setStorage(Boolean storage) {
        this.storage = storage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seedContentProcessRule.conditional
     *
     * @return the value of seedContentProcessRule.conditional
     *
     * @mbggenerated
     */
    public Boolean getConditional() {
        return conditional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seedContentProcessRule.conditional
     *
     * @param conditional the value for seedContentProcessRule.conditional
     *
     * @mbggenerated
     */
    public void setConditional(Boolean conditional) {
        this.conditional = conditional;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seedContentProcessRule.conditionPattern
     *
     * @return the value of seedContentProcessRule.conditionPattern
     *
     * @mbggenerated
     */
    public String getConditionpattern() {
        return conditionpattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seedContentProcessRule.conditionPattern
     *
     * @param conditionpattern the value for seedContentProcessRule.conditionPattern
     *
     * @mbggenerated
     */
    public void setConditionpattern(String conditionpattern) {
        this.conditionpattern = conditionpattern == null ? null : conditionpattern.trim();
    }
}